[package]
name = "compiler"
version = "0.1.0"
edition = "2018"

[build-dependencies]
lalrpop = "0.19.6"

[dependencies]
lalrpop-util = "0.19.6"
regex = "1"
global_counter = "0.2.2"
log = "0.4.14"
simple_logger = "1.16.0"
anyhow = "1.0.52"